### ISSUE TITLE
Template parsing error: template: :1:48: executing

### ISSUE THREAD

**Issue by mrjones-plip** [mrjones-plip/DockStat#3]
In testing [this compose file](https://docs.docker.com/samples/wordpress/), when I ran `docker-compose up` I see this error always on the bottom of DockStat:

```
Template parsing error: template: :1:48: executing "" at <index $conf 0>: error calling index: index of untyped nil
```

Steps to reproduce:
1. create a new directory and in it create a  `docker-compose.yml` file with this contents:
   ```
    version: "3.9"
        
    services:
    db:
        image: mysql:5.7
        volumes:
        - db_data:/var/lib/mysql
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        
    wordpress:
        depends_on:
        - db
        image: wordpress:latest
        volumes:
        - wordpress_data:/var/www/html
        ports:
        - "8000:80"
        restart: always
        environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
    volumes:
    db_data: {}
    wordpress_data: {}
   ```
2. run `docker-compose up`
3. in another terminal run `./DockStat.sh`. 

Expected: No errors are shown
Actual: error is shown at bottom of screen
